dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"  # 3.6 development branch
  - "3.8-dev"  # 3.7 development branch
install:
  - python setup.py -q install
script:
  - python test.py
